[general]

import = [
    "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

[window]

decorations = "Full"
padding.x = 16
padding.y = 16

[font]

size = 10
offset.x = 4
offset.y = 4

normal.family = "Consolas"
normal.style = "Regular"

bold.family = "Consolas"
bold.style = "Bold"

italic.family = "Consolas"
italic.style = "Italic"

bold_italic.family = "Consolas"
bold_italic.style = "Bold Italic"

[cursor]

style.blinking = "Never"

[terminal.shell]

program = "wsl"